export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_PROCESSING = 'FETCH_DATA_PROCESSING';

export const SORTING_IN_RANDOM = 'SORTING_IN_RANDOM';
export const SORTING_IN_RANDOM_PROCESSING = 'SORTING_IN_RANDOM_PROCESSING';
